### ISSUE TITLE
Table Change

### ISSUE THREAD

**Issue by sunyu912** [K12Ventures/K12Ventures.github.io#17]
The table is too wide in mobile. Maybe we can remove the last column, and put the grade level info on the student or school column.

<img width="1145" alt="screen shot 2018-10-04 at 8 24 32 am" src="https://user-images.githubusercontent.com/1639351/46484643-014fa080-c7af-11e8-810c-ae308cef68d0.png">

**Comment by cassilam** [comment]
Removed the last column and merged it with school
