### ISSUE TITLE
Desktop Advisor Layout Off (Please Sync Up Code First)

### ISSUE THREAD

**Issue by sunyu912** [K12Ventures/K12Ventures.github.io#19]
<img width="1168" alt="screen shot 2018-10-04 at 10 16 50 am" src="https://user-images.githubusercontent.com/1639351/46491098-9f973280-c7be-11e8-8ef8-68bb7712b3f1.png">

**Comment by cassilam** [comment]
Fixed the layout issue after some div and css adjustments
