### ISSUE TITLE
Contact Form Not Getting Emails

### ISSUE THREAD

**Issue by sunyu912** [K12Ventures/K12Ventures.github.io#21]
@cassilam Our contact us form only receives the message, but not the email and name. Probably we forget to post something. Could you check it? You can see the coding minds website as an example.

<img width="603" alt="screen shot 2018-10-11 at 11 53 10 am" src="https://user-images.githubusercontent.com/1639351/46827012-5d389d00-cd4c-11e8-8a33-7fa6bc53dc48.png">

**Comment by cassilam** [comment]
Can you check the newest form submission? I sent a test submission. What might have happened is that they didn't fill out their name and email. I have added a requirement for them to fill that information out.

**Comment by sunyu912** [comment]
[image: Screen Shot 2018-10-11 at 12.41.10 PM.png]

**Comment by cassilam** [comment]
I can't see the attached image
