### ISSUE TITLE
Footer Text Update

### ISSUE THREAD

**Issue by sunyu912** [K12Ventures/K12Ventures.github.io#24]
"K12 Ventures is a startup incubator and venture capital that provides early-stage startup accelerators, funding and mentorship for the young entrepreneurs"

=>

"K12 Ventures is a startup incubator that provides early-stage startup accelerators, funding and mentorship for the young entrepreneurs. 

K12 Ventures is a 501 (C) 3 Non-Profit Organization | Tax ID 84-1808528"

**Comment by cassilam** [comment]
Updated text
