### ISSUE TITLE
Introduction Test Update in Section "About K12 Ventures"

### ISSUE THREAD

**Issue by sunyu912** [K12Ventures/K12Ventures.github.io#27]
"K12 Ventures is a startup incubator and venture capital that provides early-stage startup accelerators, funding and mentorship for the young entrepreneurs - from kindergarteners to high school seniors."

=> 

"K12 Ventures is 501 (c)(3) non-profit startup incubator that provides early-stage startup accelerators, funding and mentorship for the young entrepreneurs - from kindergarteners to high school seniors."

**Comment by cassilam** [comment]
Updated the intro for "about k12 ventures"
