### ISSUE TITLE
Add Board Of Directors (Move some people to this section from Advisors)

### ISSUE THREAD

**Issue by sunyu912** [K12Ventures/K12Ventures.github.io#31]
We need to create a new section "Board Of Directors" and list:

- Edmond
- Thomas
- Yu Sun
- Sha Zhang

Then, in Board of Advisors , list the rest:
In addition, please add:
- Liping Zhou, Senior Software Engineer, Amazon
- Zach Kysar, Software Engineer, Google

**Comment by cassilam** [comment]
Added a Board of Directors section and updated advisors and directors list
