### ISSUE TITLE
Event Video and Photos

### ISSUE THREAD

**Issue by sunyu912** [K12Ventures/K12Ventures.github.io#34]
We had a Youtube video for each of the past events. And also photos. 

Could we add these link/embedded content somewhere?

Spring 2019
https://www.youtube.com/watch?v=hqHDBEvm1CU
https://photos.app.goo.gl/dBn5zUEFurxMyZNc7

Fall 2018
https://www.youtube.com/watch?v=qcDefolKvfQ
https://lightroom.adobe.com/shares/67ee3f5c74ec4d4199147117b70f480e

We should put some of the good photos in the page somewhere to promote the organization and event.

**Comment by cassilam** [comment]
added links for event videos and photos in past events section
