### ISSUE TITLE
Industry Partner Logos

### ISSUE THREAD

**Issue by sunyu912** [K12Ventures/K12Ventures.github.io#6]
https://codingmindsacademy.com/img/my/logo1.png

https://www.chronaly.com/assets/images/logo-tagline.png

http://107.23.13.89/wp-content/uploads/2018/01/black-and-blue.png

![image](https://user-images.githubusercontent.com/1639351/46222893-9c0b3380-c306-11e8-9973-81156ecffd06.png)

**Comment by cassilam** [comment]
Added logos
